# Generated by Django 5.1.2 on 2024-10-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام درس")),
            ],
            options={
                "verbose_name": "درس\u200cها",
                "verbose_name_plural": "درس\u200cها",
            },
        ),
        migrations.CreateModel(
            name="LessonScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="نمرات")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.lesson",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمره درس\u200cها",
                "verbose_name_plural": "نمره درس\u200cها",
            },
        ),
    ]
