# Generated by Django 5.1.2 on 2024-10-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم")),
            ],
        ),
        migrations.RemoveField(
            model_name="lessonscore",
            name="lesson",
        ),
        migrations.CreateModel(
            name="ProductSold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="تعداد")),
                ("sell_date_time", models.DateTimeField(verbose_name="زمان فروش")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="LessonScore",
        ),
    ]
